#
# Copyright (C) 2022 AVNET Embedded, <avnet-embedded.eu>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation version 2.
#
# This program is distributed "as is" WITHOUT ANY WARRANTY of any
# kind, whether express or implied; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

dtb-$(CONFIG_IMX8MN) += \
	msc-osm-imx8m-nano-8NQ1G40-module.dtb \
	msc-osm-imx8m-nano-8NQ1G160-module.dtb \
	msc-osm-imx8m-nano-02N0800I-module.dtb \
	msc-osm-imx8m-nano-04N0800E-module.dtb \
	msc-osm-imx8m-nano-DC-004-module.dtb \
	msc-osm-imx8m-nano-QC-003-module.dtb \
	overlay-sm2f-osm-ad-001.dtb \
	overlay-baseboard-vebo.dtb \
	overlay-baseboard-ep1.dtb \
	overlay-baseboard-afts2019.dtb \
	overlay-display-lvds-ama-121a01.dtb \
	overlay-camera-ov5640.dtb 

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
