#
# Copyright (C) 2022 Avnet Embedded GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation version 2.
#
# This program is distributed "as is" WITHOUT ANY WARRANTY of any
# kind, whether express or implied; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

dtb-$(CONFIG_IMX8MP) += \
	msc-sm2s-imx8mpl-03N0700I-module.dtb \
	msc-sm2s-imx8mp-03N0E10I-module.dtb \
	msc-sm2s-imx8mp-14N0700I-module.dtb \
	msc-sm2s-imx8mp-14N0740I-module.dtb \
	msc-sm2s-imx8mp-24N0600I-module.dtb \
	msc-sm2s-imx8mp-24N0680I-module.dtb \
	msc-sm2s-imx8mp-24N0E10I-module.dtb \
	msc-sm2s-imx8mp-25N0600I-module.dtb \
	msc-sm2s-imx8mp6-14N0600E-module.dtb \
	msc-sm2s-imx8mp6-14N0E00I-module.dtb \
	msc-sm2s-imx8mp-14N0741I-module.dtb \
	msc-sm2s-imx8mp6-15N0700E-module.dtb \
	overlay-baseboard-ep1.dtb \
	overlay-baseboard-vebo.dtb \
	overlay-cam0-ov5640.dtb \
	overlay-cam1-ov5640.dtb \
	overlay-cam2-basler.dtb \
	overlay-dsi-boe-gv101wum-ls0.dtb \
	overlay-dsi-rm67191.dtb \
	overlay-dsi-xinli-x078dtlt-119.dtb \
	overlay-hdmi.dtb \
	overlay-lvds0-ama-070a04.dtb \
	overlay-lvds0-ama-101a01.dtb \
	overlay-lvds0-ama-101a07.dtb \
	overlay-lvds0-ama-121a01.dtb \
	overlay-lvds0-auo-p215hvn01.dtb \
	overlay-lvds0-innolux-G156HCE-L01.dtb \
	overlay-lvds1-ama-070a04.dtb \
	overlay-lvds1-ama-101a01.dtb \
	overlay-lvds1-ama-101a07.dtb \
	overlay-lvds1-ama-121a01.dtb \
	overlay-video-pll-ss.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
